"""Create users table

Revision ID: d207ea5e4480
Revises: cbb246f91275
Create Date: 2026-07-21 18:10:46.250500

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d207ea5e4480"
down_revision: Union[str, Sequence[str], None] = "cbb246f91275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
